version: '3.8'

services:
  server:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
      - "40400-40690:40400-40690"
    command: ["python3", "-u", "server.py"]
