version: '3.8'

services:
  server:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
      - "${GAME_PORTS_MIN}-${GAME_PORTS_MAX}:${GAME_PORTS_MIN}-${GAME_PORTS_MAX}"
    command: ["python3", "-u", "server.py"]
