version: '3.8'

services:
  server:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
      - "40100-40150:40100-40150"
    command: ["python3", "server.py"]
